name: PHP Composer

on:
  push:
    branches: [ "7.x-1.x" ]
#    tags:
#      - /^\d\.x-\d+\.\d+-.+$/
#      - /^\d\.x-\d+\.\d+$/
#      - /^v\d+\.\d+\.\d+-.+$/
#      - /^v\d+\.\d+\.\d+$/
#      - /^\d+\.\d+\.\d+$/


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: nanasess/setup-php@v3
      with:
        php-version: '7.4'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Check composer version
      run: composer -V

    - name: Composer install
      run: composer install --no-dev --optimize-autoloader

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

    - name: Compress build and create release file
      uses: a7ul/tar-action@v1.1.0
      id: compress
      with:
        command: c
        cwd: ./
        files: |
          ./*
        outPath: ghtest.tar.gz

